apiVersion: apps.starport.cloud/v1
kind: NodeSet
metadata:
  name: titus-1
  namespace: archway
spec:
  config:
    resetDataOnImageUpgrade: true
    nodes:
      configOverride:
        config:
          - group: rpc
            key: cors_allowed_origins
            value:
              stringList: ["*"]
          - group: instrumentation
            key: prometheus
            value:
              bool: true
        app:
          - group: api
            key: enabled-unsafe-cors
            value:
              bool: true
          - group: telemetry
            key: enabled
            value:
              bool: true
          - group: telemetry
            key: enable-service-label
            value:
              bool: true
          - group: telemetry
            key: prometheus-retention-time
            value:
              int: 30
          - group: telemetry
            key: service-name
            value:
              string: archway
          - group: telemetry
            key: global-label
            value:
              stringListList: [["chain_id", "titus-1"]]
  app:
    cliName: archwayd
    daemonName: archwayd
    name: archway
  expose:
    domain: titus-1.archway.tech
    api: true
    grpc: true
    rpc: true
    p2p: true
  image:
    name: docker.io/archwaynetwork/archwayd
    version: sha-8e3e5be
    imagePullPolicy: Always
  init:
    assets:
      - 10000000000000000000utitus
    accounts:
      - address: archway1zsetek833g3upk2dgc56nqskm8tg804y6vvw0l
        coins:
          - 100000000000000000utitus
    bondDenom: utitus
    chainID: titus-1
  moniker: archway
  persistence:
    autoResize:
      enabled: true
      increment: 5G
      threshold: 80
    size: 5G
  replicas: 2
  resources:
    restServer: {}
    sentry: {}
    validator: {}
  serviceMonitorLabels:
    release: monitoring-stack
  sdkVersion: stargate
