apiVersion: apps.starport.cloud/v1
kind: NodeSet
metadata:
  name: titus-1
  namespace: testnets
spec:
  binaryName: archwayd
  config:
    nodes:
      configOverride:
        app:
        - group: api
          key: enabled-unsafe-cors
          value:
            bool: true
        - group: telemetry
          key: enabled
          value:
            bool: true
        - group: telemetry
          key: enable-service-label
          value:
            bool: true
        - group: telemetry
          key: prometheus-retention-time
          value:
            int: 30
        - group: telemetry
          key: service-name
          value:
            string: archway
        - group: telemetry
          key: global-label
          value:
            stringListList:
            - - chain_id
              - titus-1
        config:
        - group: rpc
          key: cors_allowed_origins
          value:
            stringList:
            - '*'
        - group: instrumentation
          key: prometheus
          value:
            bool: true
    resetDataOnImageUpgrade: true
  expose:
    api: true
    domain: titus-1.archway.tech
    grpc: true
    p2p: true
    rpc: true
  image:
    name: docker.io/archwaynetwork/archwayd
    version: NODE_VERSION
    imagePullPolicy: Always
  init:
    assets:
    - 10000000000000000000utitus
    bondDenom: utitus
    chainID: titus-1
    faucet:
      creditAmount: 10000000
      denoms:
      - utitus
      domain: faucet.titus-1.archway.tech
      funds: 100000000000000000utitus
      legacySend: false
      maxCredit: 100000000
      replicas: 1
  moniker: archway
  persistence:
    autoResize:
      enabled: false
      increment: 5G
      threshold: 80
    size: 160G
  replicas: 2
  resources:
    sentry: {}
    validator: {}
  serviceMonitorLabels:
    release: monitoring-stack
