name: Deploy Titus Test Network

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  install-titus:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GCR
        uses: docker/login-action@v1
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCR_JSON_KEY }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: Dockerfile
          tags: gcr.io/tendermint-dev/archway:${{ github.sha }}

      - name: Find and Replace
        uses: nguyenvanuyn96/str-find-and-replace-action@0.0.5
        with:
          find: NODE_VERSION
          replace: ${{ github.sha }}
          include: ci/titus-1.yaml

      - name: Deploy Chain
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.GKE_TENDERMINT_DEV_US_EAST1_STARPORT_CLOUD_DEV_KUBECONFIG_B64 }}
          command: apply -n archway -f ci/titus-1.yaml

